# Generated by Django 5.0.6 on 2024-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.AddField(
            model_name='category',
            name='task',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
