# Generated by Django 5.0.6 on 2024-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('is_complete', models.BooleanField(default=False)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
