# Generated by Django 5.0.6 on 2024-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_categories'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
